[book]
authors = ["Yehuda Katz"]
language = "en"
src = "src"
title = "Color System Documentation"

[output.html]
site-url = "/algebraic/"
additional-js = ["src/js/mermaid.min.js", "src/js/mermaid-init.js"]
additional-css = ["src/css/color-system.css", "src/css/docs.css"]

